######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 20 17:36:31 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include src
INCLUDEPATH += . include

# Input
HEADERS += include/mainwindow.h
FORMS += src/mainwindow.ui
SOURCES += src/main.cpp src/mainwindow.cpp
